# Generated by Django 5.0.6 on 2024-07-03 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamentoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('ubicacionID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, null=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidadID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255)),
                ('departamentoID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnero.departamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('medicoID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_medicos',
            fields=[
                ('horarioID', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('departamentoID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnero.departamentos')),
                ('especialidadID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.especialidades')),
                ('medicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.medicos')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('citaID', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=25)),
                ('departamentoID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnero.departamentos')),
                ('horarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.horario_medicos')),
                ('medicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.medicos')),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='ubicacionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.ubicaciones'),
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('TurnoID', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=25)),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('citaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.citas')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnero.usuarios')),
            ],
        ),
    ]
