# Generated by Django 5.0.6 on 2024-07-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0002_rename_turnoid_turnos_turnoid_alter_turnos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
