# Generated by Django 5.0.6 on 2024-07-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0003_usuarios_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
