# Generated by Django 5.0.6 on 2024-07-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnero', '0005_remove_citas_horarioid_citas_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='hora',
        ),
        migrations.AddField(
            model_name='citas',
            name='horarioID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turnero.horario_medicos'),
            preserve_default=False,
        ),
    ]
